# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdaeb3924a777c796dfb3b1e682c1568ab051548f0657c6173f0b2129f1617b250047a4d29be6bfac0b292087f14e7d0c5255d2c21c17d3607bd3641fb937c02

test:
  secret_key_base: cf785c6aed8b201414b9381981f075454b84291f7fd8d8059892e4fed627d9a45626434b4b6c9393524e581383ebc80a167a9fe7c36b7b7c70fee4c3b2148a74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
